apiVersion: widgets.templates.krateo.io/v1beta1
kind: Flex
metadata:
  name: page-meetup-health
  namespace: '{{ include "page.tierNamespace" (dict "ctx" . "tier" "common") }}'
spec:
  resourcesRefs:
    items:
      - apiVersion: widgets.templates.krateo.io/v1beta1
        id: meetup-health-header
        name: meetup-health-header
        namespace: '{{ include "page.tierNamespace" (dict "ctx" . "tier" "common") }}'
        resource: pageheaders
        verb: GET
      - apiVersion: widgets.templates.krateo.io/v1beta1
        id: meetup-health-pie
        name: meetup-health-pie
        namespace: '{{ include "page.tierNamespace" (dict "ctx" . "tier" "common") }}'
        resource: piecharts
        verb: GET
      - apiVersion: widgets.templates.krateo.io/v1beta1
        id: meetup-health-table
        name: meetup-health-table
        namespace: '{{ include "page.tierNamespace" (dict "ctx" . "tier" "common") }}'
        resource: tables
        verb: GET
  widgetData:
    allowedResources:
      - pageheaders
      - piecharts
      - tables
    gap: middle
    items:
      - resourceRefId: meetup-health-header
      - resourceRefId: meetup-health-pie
      - resourceRefId: meetup-health-table
    vertical: true
